import React from 'react';
import {
  Droplet,
  BookOpen,
  Dumbbell,
  Brain,
  Flame,
  Moon,
  ArrowUp,
  Bell,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  X,
  Eye,
  Users,
  Grid3x3,
  MapPin,
  Lock,
  Mic,
  Pill,
  Plus,
  RefreshCw,
  Shield,
  Sparkle,
  Sparkles,
  Target,
  UsersRound,
  Heart,
  Activity,
  Calendar,
  Clock,
  Home as HomeIcon,
  ListChecks,
  MoreHorizontal,
  Settings as SettingsIcon,
  Wallet,
  Notebook,
  Vault as VaultIcon,
  ShoppingCart,
  Baby,
  HeartHandshake,
  CircleDot,
  Compass,
  type LucideIcon,
} from 'lucide-react-native';

export const iconMap: Record<string, LucideIcon> = {
  water: Droplet,
  book: BookOpen,
  dumbbell: Dumbbell,
  brain: Brain,
  flame: Flame,
  moon: Moon,
  arrowUp: ArrowUp,
  bell: Bell,
  camera: Camera,
  check: Check,
  chevL: ChevronLeft,
  chevR: ChevronRight,
  chevron: ChevronDown,
  close: X,
  eye: Eye,
  family: UsersRound,
  grid: Grid3x3,
  location: MapPin,
  lock: Lock,
  mic: Mic,
  pill: Pill,
  plus: Plus,
  refresh: RefreshCw,
  shield: Shield,
  sparkle: Sparkle,
  sparkles: Sparkles,
  target: Target,
  viewers: Users,
  heart: Heart,
  activity: Activity,
  calendar: Calendar,
  clock: Clock,
  home: HomeIcon,
  list: ListChecks,
  more: MoreHorizontal,
  settings: SettingsIcon,
  wallet: Wallet,
  notebook: Notebook,
  vault: VaultIcon,
  errand: ShoppingCart,
  baby: Baby,
  couple: HeartHandshake,
  dot: CircleDot,
  compass: Compass,
};

export const Icon = ({
  name,
  size = 18,
  color = '#fff',
  strokeWidth = 1.8,
}: {
  name: keyof typeof iconMap | string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) => {
  const Cmp = iconMap[name] ?? CircleDot;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} />;
};
